/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

/**
 *
 * @author Sebastian Guillen
 */

public class Interfaz extends javax.swing.JFrame {
    Grafo Grafo = new Grafo();
    /**
     * Creates new form NewJFrame
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }
private void IntroNodo(){
    String pnew = Entrada.getText();
    if (pnew != null && !pnew.trim().isEmpty()){
        Grafo.NuevoNodo(pnew);
        Salida.setText(Grafo.VerGrafo());
        Entrada.setText("");
        Entrada.requestFocusInWindow();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InsertarArco = new javax.swing.JButton();
        InsertarNodo1 = new javax.swing.JButton();
        Entrada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        InsertarArco.setText("Insertar Arco");
        InsertarArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarArcoActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarArco, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, 30));

        InsertarNodo1.setText("Insertar Nodo");
        InsertarNodo1.setActionCommand("Insertar Archivo");
        InsertarNodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarNodo1ActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarNodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 30));

        Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaActionPerformed(evt);
            }
        });
        Entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EntradaKeyPressed(evt);
            }
        });
        getContentPane().add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 110));

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 470, 150));

        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarArcoActionPerformed
String origen = "";
String destino = "";
origen = JOptionPane.showInputDialog("Origen:");
destino = JOptionPane.showInputDialog("Destino:");
if (Grafo.ExisteVertice(origen) && Grafo.ExisteVertice(destino)){
 Grafo.NuevaArista(origen, destino);
}    
Salida.setText(Grafo.VerGrafo());
    }//GEN-LAST:event_InsertarArcoActionPerformed

    private void InsertarNodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarNodo1ActionPerformed
JFileChooser Selector = new JFileChooser();
int Resultado = Selector.showOpenDialog(this);
if (Resultado == JFileChooser.APPROVE_OPTION){
    java.io.File ArchivoSelec = Selector.getSelectedFile();
    Salida.setText("Ruta del archivo seleccionado: " + ArchivoSelec.getAbsolutePath());
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccionaste: " + ArchivoSelec.getAbsolutePath());
}else{
    Salida.setText("El usuario no insertó archivos.");
}
// TODO add your handling code here:
IntroNodo();
    }//GEN-LAST:event_InsertarNodo1ActionPerformed

    private void EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaActionPerformed

    private void EntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaKeyPressed
if (evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER){
    IntroNodo();
}
    }//GEN-LAST:event_EntradaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entrada;
    private javax.swing.JButton InsertarArco;
    private javax.swing.JButton InsertarNodo1;
    private javax.swing.JTextArea Salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
