/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;


/**
 *
 * @author Sebastian Guillen
 */

public class Interfaz extends javax.swing.JFrame {
    Grafo Grafo = new Grafo();
    Grafico grafico;
    String usuariosString;
    String relacionesString;
    /**
     * Creates new form NewJFrame
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CrearGrafo = new javax.swing.JButton();
        insertarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        insertarArco = new javax.swing.JButton();
        insertarNodo = new javax.swing.JButton();
        graphJPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CrearGrafo.setText("Crear grafo");
        CrearGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(CrearGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 30));

        insertarArchivo.setText("Insertar Archivo");
        insertarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(insertarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 150, 30));

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 470, 150));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 40));

        insertarArco.setText("Agregar relaciones");
        insertarArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarArcoActionPerformed(evt);
            }
        });
        getContentPane().add(insertarArco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 140, 30));

        insertarNodo.setText("Agregar usuarios");
        insertarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarNodoActionPerformed(evt);
            }
        });
        getContentPane().add(insertarNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 140, 30));
        getContentPane().add(graphJPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 650, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearGrafoActionPerformed
        String usuario;
        Scanner scannerUsuarios = new Scanner(this.usuariosString);
        while (scannerUsuarios.hasNextLine()){
            usuario = scannerUsuarios.nextLine();
            Grafo.NuevoNodo(usuario);
        }
        String[] relacion;
        String origen;
        String destino;
        Scanner scannerRelaciones = new Scanner(this.relacionesString);
        while (scannerRelaciones.hasNextLine()){
            relacion = scannerRelaciones.nextLine().split(",");
            origen = relacion[0].trim();
            destino = relacion[1].trim();
            Grafo.NuevaArista(origen, destino);
        }
        Salida.setText(Grafo.VerGrafo());
        this.grafico = new Grafico(this.Grafo);
        this.grafico.generarGrafoGs();
        this.grafico.mostrarGrafoEnPanel(graphJPanel1);
    }//GEN-LAST:event_CrearGrafoActionPerformed

    private void insertarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarArchivoActionPerformed
        JFileChooser Selector = new JFileChooser();
        int Resultado = Selector.showOpenDialog(this);
        if (Resultado == JFileChooser.APPROVE_OPTION){
            File archivoSeleccionado = Selector.getSelectedFile();
            String nombreArchivo = Selector.getName(archivoSeleccionado);
            JOptionPane.showMessageDialog(this, "Archivo: '" + nombreArchivo + "' seleccionado");
            Lector lector = new Lector(archivoSeleccionado);
            lector.leer();
            this.usuariosString = lector.getUsuariosString();
            this.relacionesString = lector.getRelacionesString();
            System.out.println("Los usuarios son: " + this.usuariosString);
            System.out.println("Las relaciones son: " + this.relacionesString);
        }else{
            JOptionPane.showMessageDialog(this, "El usuario no insertó archivos.");
        }
    }//GEN-LAST:event_insertarArchivoActionPerformed

    private void insertarArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarArcoActionPerformed
        // TODO add your handling code here:
        String origen = "";
        String destino = "";
        origen = JOptionPane.showInputDialog("Inserte el usuario de origen (Ejemplo: @pepe):");
        destino = JOptionPane.showInputDialog("Inserte el usuario de destino (Ejemplo: @marcos):");
        if (Grafo.ExisteVertice(origen) && Grafo.ExisteVertice(destino)){
            Grafo.NuevaArista(origen, destino);
            if (this.grafico != null) {
                this.grafico.generarGrafoGs();
                this.grafico.mostrarGrafoEnPanel(graphJPanel1);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se ha encontrado el usuario de origen y/o destino, intente nuevamente");
        }    
        Salida.setText(Grafo.VerGrafo());
    }//GEN-LAST:event_insertarArcoActionPerformed

    private void insertarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarNodoActionPerformed
        // TODO add your handling code here:
        String pnew = JOptionPane.showInputDialog("Inserte el usuario (Ejemplo: @lucas):");;
        if (pnew != null && !pnew.trim().isEmpty()){
            Grafo.NuevoNodo(pnew);
            if (this.grafico != null) {
                this.grafico.generarGrafoGs();
                this.grafico.mostrarGrafoEnPanel(graphJPanel1);
            }
        }
            Salida.setText(Grafo.VerGrafo());
    }//GEN-LAST:event_insertarNodoActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearGrafo;
    private javax.swing.JTextArea Salida;
    private javax.swing.JPanel graphJPanel1;
    private javax.swing.JButton insertarArchivo;
    private javax.swing.JButton insertarArco;
    private javax.swing.JButton insertarNodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFileChooser fileChooser;
}
